[general]
default-save-path=~/Downloads

[ui]
styleset-name=catppuccin
timestamp-format=2006-01-02 15:04
this-day-time-format=15:04
this-year-time-format=Jan 02 15:04
sidebar-width=28
preview-height=12
mouse-enabled=true
fuzzy-complete=true
sort=-date

[viewer]
pager=less -R
alternatives=text/plain,text/html
show-images=false
header-layout=From,To,Cc,Date,Subject

[compose]
editor=nvim
header-layout=To,From,Cc,Subject
reply-to-all=false

[filters]
text/html=w3m -T text/html -dump -cols 80 -o document_charset=UTF-8 -o display_image=false
text/plain=cat
image/*=catimg -

[hooks]
mail-received=sh -c 'if [ "$(uname)" = "Darwin" ]; then osascript -e "display notification \"New email\" with title \"aerc\""; else notify-send -a aerc "New email"; fi'
