[messages]
q = :prompt 'Quit?' quit<Enter>
j = :next<Enter>
k = :prev<Enter>
g = :select 0<Enter>
G = :select -1<Enter>
<Enter> = :view<Enter>
s = :split<Enter>
S = :vsplit<Enter>
d = :choose -o y 'Really delete?' delete-message<Enter>
D = :delete<Enter>
a = :archive flat<Enter>
rr = :reply -a<Enter>
rq = :reply -aq<Enter>
Rr = :reply<Enter>
Rq = :reply -q<Enter>
c = :compose<Enter>
/ = :search<space>
n = :next-result<Enter>
N = :prev-result<Enter>
J = :next-folder<Enter>
K = :prev-folder<Enter>
v = :mark -t<Enter>
V = :mark -v<Enter>
T = :toggle-threads<Enter>
<C-r> = :check-mail<Enter>
<C-n> = :next-tab<Enter>
<C-p> = :prev-tab<Enter>

[messages:folder=Drafts]
<Enter> = :recall<Enter>

[view]
q = :close<Enter>
/ = :toggle-key-passthrough<Enter>/
H = :toggle-headers<Enter>
rr = :reply -a<Enter>
rq = :reply -aq<Enter>
Rr = :reply<Enter>
Rq = :reply -q<Enter>
d = :choose -o y 'Really delete?' delete-message<Enter>
D = :delete<Enter>
a = :archive flat<Enter>
f = :forward<Enter>
o = :open<Enter>
J = :next<Enter>
K = :prev<Enter>
<C-j> = :next-part<Enter>
<C-k> = :prev-part<Enter>
<C-n> = :next-tab<Enter>
<C-p> = :prev-tab<Enter>

[compose]
<C-s> = :send<Enter>
<C-q> = :close<Enter>
<tab> = :next-field<Enter>
<backtab> = :prev-field<Enter>
<C-n> = :next-tab<Enter>
<C-p> = :prev-tab<Enter>

[compose::review]
y = :send<Enter>
n = :abort<Enter>
e = :edit<Enter>
p = :postpone<Enter>
v = :preview<Enter>
